name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
 build:
   runs-on: ['self-hosted']
   steps:
    - name: checkout code
      uses: actions/checkout@2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build library service
      run: ./gradlew clean build

    - name: Build docker image
      run: docker build -t library-service .



